const String eventListTitle = 'Events';
const String eventDetailsTitle = 'Events Details';
const String eventSearchTitle = 'Search';
const String eventSearchHint = 'Type Event Name';
const String eventBookBtnLabel = 'BOOK NOW';
const String organizer = 'Organizer';
const String aboutEvent = 'About Event';
const String loadingText = 'Please wait a moment...';
const String notFound = 'No related events found!';